### ISSUE TITLE
Integrate PowerKeePass and PSKeePass code

### ISSUE THREAD

**Issue by jkdba** [PSKeePass/PSKeePass#10]
As discussed we will integrate these two projects using the PowerKeePass module code as a backend framework for the frontend module code from original PSKeePass project.

### Todo's:

- [x] Go through PSKeePass cmdlets and see what backend cmdlets need to be created to support these cmdlets.
- [x] See what backend cmdlets need to be updated or modified to support features of the frontend.
- [x] Update frontend code to use backend
- [x] Update frontend to support extra features that the backend already supports.

**Comment by jkdba** [comment]
Integrated backed code, and worked through the check list.
